data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
apiVersion: v1
kind: Secret
metadata:
  name: udacprj2akscluster
  namespace: default
---
data:
  host.master: OFFKeUxCVldWZmR2V21ucVZncmFJN0MyVC83cTFpc2lxai94cWFsRFhFbm9QMUlCVGFQYWxnPT0=
  host.function.default: bHRnb0FlWW51eHZvRjg0YTlFVWIwVTRKV1RXdGVrbmR6OWNUa0FWeDBTWW55L0piVXBsY2tnPT0=
  host.systemKey.default: dlZpNS9kTGFqVllNamFTZzhIM0lDa2hKb3diakhrYmFYMWZhSy8vZUVNVGxRa3lxR2d1bGFnPT0=
  functions.createadvertisement.default: MG52NE1sOVFKRllFeEltQUlhVlhQUm11czdEY2FBT096dU5MazV2Ym5NZDlueFkwN2hKLzlnPT0=
  functions.deleteadvertisement.default: VW1SZ0tSb1h6NUtEaVlZZTlJZ0hKNjBkUFFNZjZhSGE2dmFRVlV6eW5OcmlvbVBVWllCMll3PT0=
  functions.getadvertisement.default: bEp1VU9RMk1USGI0bmJDVUxERGFrQnBrdkQ4ZEQ4cHdSSEpHOE1WSzhjLzJLQTM1QkhUZXlnPT0=
  functions.getadvertisements.default: Yjc4aHUyZ25SRnN3Rks5UUQvak5CbUduZ2lpRG5oTGVsNk5ubmZ5RzRZbHVFcTdNdW9HbkdnPT0=
  functions.getpost.default: OGtRWElyM1V5Y1B5OVpkRGxUbmtCSndhTC8wTmN6QlhCZnoxaTIzVHpNNkZkNmk1MTFiQXpnPT0=
  functions.getposts.default: VVJ3QXJTQnBXaGpwUjdhU2p3UWNjcGFzRGVZLzNSd0J0U3RrV1NWYW1jMmMzazJKQTJYS2xRPT0=
  functions.updateadvertisement.default: Z210czk3R1ZSQkwxMWVDanNoamEycmcyMEZ1T3c1VmdDMFhrWWNRVUFOMHcvVmsxaElHWXdnPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-udacprj2akscluster
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: udacprj2akscluster-function-keys-identity-svc-act
  namespace: default
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
  namespace: default
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: udacprj2akscluster-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: udacprj2akscluster-function-keys-identity-svc-act-functions-keys-manager-rolebinding
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: udacprj2akscluster-http
  namespace: default
spec:
  selector:
    app: udacprj2akscluster-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacprj2akscluster-http
  namespace: default
  labels:
    app: udacprj2akscluster-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacprj2akscluster-http
  template:
    metadata:
      labels:
        app: udacprj2akscluster-http
    spec:
      containers:
      - name: udacprj2akscluster-http
        image: udacprj2contregistry.azurecr.io/udacprj2funccontainer
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-udacprj2akscluster
        envFrom:
        - secretRef:
            name: udacprj2akscluster
      serviceAccountName: udacprj2akscluster-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacprj2akscluster
  namespace: default
  labels:
    app: udacprj2akscluster
spec:
  selector:
    matchLabels:
      app: udacprj2akscluster
  template:
    metadata:
      labels:
        app: udacprj2akscluster
    spec:
      containers:
      - name: udacprj2akscluster
        image: udacprj2contregistry.azurecr.io/udacprj2funccontainer
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: udacprj2akscluster
      serviceAccountName: udacprj2akscluster-function-keys-identity-svc-act
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: udacprj2akscluster
  namespace: default
  labels:
    deploymentName: udacprj2akscluster
spec:
  scaleTargetRef:
    deploymentName: udacprj2akscluster
  triggers:
  - type: eventgridtrigger
    metadata:
      type: eventGridTrigger
      name: event
      direction: in
      eventHubName: testhub
      connection: EVENT_CONN_STRING
---

